apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: digital-bank-backends-visa-node
    tier: backend
    tier-name: backend-visa    
  name: digital-bank-backends-visa-node-deployment
  namespace: digibank-backends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digital-bank-backends-visa-node
  strategy: {}
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
      labels:
        app: digital-bank-backends-visa-node
        tier: backend
        tier-name: backend-visa              
    spec:
      containers:
      - image: "{{ .Values.image.visa_node }}"
              
        name: digital-bank-backends-visa-node
        ports:
          - name: visa-port
            containerPort: 3000        
        resources: {}
status: {}

