apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: inventory-instrumentation
  namespace: digibank
spec:
  exporter:
    endpoint: http://appdynamics-otel-collector-service.appdynamics.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest    
  env:
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_LOG_LEVEL
      value: "info"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp,logging"
 
